deployment:
  spire: true
  spireIntegrationOperator: true

# spire configuration that will be used by both spire-integration-operator and spire charts
spireConfiguration:
  clusterName: "example-cluster"
  trustDomain: "example.org"
  server:
    # by default root CA will be valid for 3 years
    root_ca_ttl: "26280h"
