apiVersion: v2
name: intents-operator
description: Otterize intents operator
type: application
version: 1.0.35
appVersion: v1.2.0
home: https://github.com/otterize/intents-operator
sources:
  - https://github.com/otterize/intents-operator
