apiVersion: v2
name: intents-operator
description: Otterize intents operator
type: application
version: 1.0.25
appVersion: v1.1.11
home: https://github.com/otterize/intents-operator
sources:
  - https://github.com/otterize/intents-operator
