apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otterize-intents-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otterize-intents-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: intents-operator-controller-manager
  namespace: {{ .Release.Namespace }}
