apiVersion: v2
name: credentials-operator
description: credentials-operator
type: application
version: 1.0.23
appVersion: v1.3.0
home: https://github.com/otterize/credentials-operator
sources:
  - https://github.com/otterize/credentials-operator
