apiVersion: v2
name: credentials-operator
description: credentials-operator
type: application
version: 1.1.3
appVersion: v1.3.2
home: https://github.com/otterize/credentials-operator
sources:
  - https://github.com/otterize/credentials-operator
