apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "{{ .Values.agent.logLevel }}"
      server_address = "{{ include "spire.fullname" . }}-server"
      server_port = "{{ .Values.server.service.port }}"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = {{ .Values.spire.trustDomain | quote }}
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = {{ .Values.spire.clusterName | quote }}
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = {{ .Values.spire.agent.skipKubeletVerification }}
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }
